export const account = [
  { id: 1, username: 'admin' },
  { id: 2, username: 'admin1' },
  { id: 3, username: 'admin2' },
  { id: 4, username: 'adminRefresh' },
  { id: 5, username: 'adminRefresh1' },
  { id: 6, username: 'adminRefresh2' },
  { id: 7, username: 'adminRefresh3' },
  { id: 8, username: 'adminRefresh4' },
  { id: 9, username: 'adminRefresh5' },
  { id: 10, username: 'adminRefresh6' },
  { id: 11, username: 'adminRefresh7' },
  { id: 12, username: 'adminRefresh8' },
  { id: 13, username: 'adminRefresh9' },
  { id: 14, username: 'adminRefresh10' },
];
